// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcOGU9i7_vnBJlu9kVM_hCxS1yE3_A5iM',
    appId: '1:700090445838:web:9cbb5ab7618dfd549c4c5f',
    messagingSenderId: '700090445838',
    projectId: 'syofb-2e44c',
    authDomain: 'syofb-2e44c.firebaseapp.com',
    storageBucket: 'syofb-2e44c.appspot.com',
    measurementId: 'G-QHEXE5653M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZk63R-dLfh4k1lb2nGC1E5r1-g7JHNec',
    appId: '1:700090445838:android:cf5a4de05df7f1879c4c5f',
    messagingSenderId: '700090445838',
    projectId: 'syofb-2e44c',
    storageBucket: 'syofb-2e44c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpXy60wZgyA76Czh3lkDC4_dHOEjG1mI',
    appId: '1:700090445838:ios:0927ce299828c6fc9c4c5f',
    messagingSenderId: '700090445838',
    projectId: 'syofb-2e44c',
    storageBucket: 'syofb-2e44c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVpXy60wZgyA76Czh3lkDC4_dHOEjG1mI',
    appId: '1:700090445838:ios:7b251bd6d7c9c6119c4c5f',
    messagingSenderId: '700090445838',
    projectId: 'syofb-2e44c',
    storageBucket: 'syofb-2e44c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
